---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Obsidian-OS
# description will be included in the image's metadata
description: This is my personal OS image.

base-image: ghcr.io/secureblue/iot-main-hardened

image-version: latest

cosign-version: none
nushell-version: none

platforms:
  - linux/amd64
  
modules:
  - from-file: common/common-modules.yml
  - from-file: common/server-modules.yml
  - from-file: common/selinux-modules.yml
  - from-file: common/final-modules.yml
